ALTER TABLE employers
-- ALTER COLUMN is_hiring SET DEFAULT FALSE; PostGreSQL
MODIFY COLUMN is_hiring SET DEFAULT {FALSE};

ALTER TABLE conversation
-- ALTER COLUMN date_sent SET DEFAULT CURRENT_TIMESTAMP; PostGreSQL
MODIFY COLUMN date_sent SET DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE conversation RENAME TO conversations;

ALTER TABLE users
ALTER COLUMN full_name SET NOT NULL,
ALTER COLUMN current_status SET NOT NULL;
